### ISSUE TITLE
Text box moves slightly when entering a message in it.

### ISSUE THREAD

**Issue by seriaati** [Void4DevYT/Mobile-Theme#2]
![Animation](https://user-images.githubusercontent.com/61446626/138657987-33676ea1-18c9-48a9-a0dd-68253f693b41.gif)

*using with bubblecord*

**Comment by Void4DevYT** [comment]
Hmm, that maybe a bubblecord problem with both themes css interfering with each other, I'll check it out when I have time. But for now, it's really unnoticeable.
